version: '3.8'
services:
  postgres:
    image: postgres:16.8
    container_name: auth-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: